package main

import (
	"encoding/json"
	"fmt"
)

type UserInfo struct {
	UserId   interface{} `json:"userId"`
	NickName interface{} `json:"nickName"`
	HeadIcon string      `json:"headIcon"`
}
type RespRetrieveUserBaseInfo struct {
	BaseResponse `json:"res"`
	Data         UserInfo `json:"data"`
}

type BaseResponse struct {
	Msg    string `json:"msg"`
	Status int    `json:"status"`
}

func main() {
	/*	res := RespRetrieveUserBaseInfo{
			BaseResponse: BaseResponse{
				Msg:"fda",
				Status:1,
			},
			Data: &UserInfo{
				NickName:"jaden",
			},
		}
		d , _ :=json.Marshal(res)
		fmt.Println(string(d))*/

	s := ""
	info := UserInfo{
		UserId:   1111,
		NickName: "fdfdfdfd",
		HeadIcon: "qqqqqqqqqqqq",
	}
	re := RespRetrieveUserBaseInfo{
		BaseResponse: BaseResponse{
			Msg:    "test",
			Status: 1,
		},
		Data: info,
	}
	json.Unmarshal([]byte(s), re)

	fmt.Println(re)
}

type AutoGenerated struct {
	BaseResponse
	Data interface{} `json:"data"`
}
